### ISSUE TITLE
CentOS 7.2 Can't compile ocaml-xen-lowlevel-libs: too few arguments to 'xc_assign_device'

### ISSUE THREAD

**Issue by TheMightyOnyx** [xenserver/buildroot#685]
Can't compile on CentOS 7.2, followed https://github.com/xenserver/buildroot/blob/master/README.md exactly but it's failing on:

```
[unpriv@CentOS-72-64-minimal buildroot]$ make
[MOCK] _build/SRPMS/ocaml-xen-lowlevel-libs-0.9.28-1.el7.centos.src.rpm
ERROR: Exception(_build/SRPMS/ocaml-xen-lowlevel-libs-0.9.28-1.el7.centos.src.rpm) Config(epel-7-x86_64) 0 minutes 10 seconds
ERROR: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps  /builddir/build/SPECS/ocaml-xen-lowlevel-libs.spec
make: *** [_build/RPMS/x86_64/ocaml-xen-lowlevel-libs-runtime-0.9.28-1.el7.centos.x86_64.rpm] Error 1
```

Attached build.log and root.log (moved old ones, tried `make` again and these are the clean logs only with lowlevel-libs related lines).

[build.txt](https://github.com/xenserver/buildroot/files/159223/build.txt)
[root.txt](https://github.com/xenserver/buildroot/files/159227/root.txt)

**Comment by simonjbeaumont** [comment]
@TheMightyOnyx we are now shipping a way to build XenServer using the RPMs that we use:

http://xenserver.org/blog/entry/a-new-year-a-new-way-to-build-for-xenserver.html

It's all container based and you should be able to compile this way.
